=== ebinsu/core-framework/core-modules/core-modules-name-query/core-modules-name-query-common/src/main/java/core/framework/namedquery/support/namedquery.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT named-queries (sql* | mongo* | fragment*)+>
<!ATTLIST named-queries
        namespace CDATA #REQUIRED
        >

<!ELEMENT fragment (#PCDATA | include | where | foreach | choose | if | bind)*>
<!ATTLIST fragment
        id CDATA #REQUIRED
        >

<!ELEMENT sql (#PCDATA | include | foreach | choose | if | bind | where)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        result-class CDATA #IMPLIED>

<!ELEMENT mongo (#PCDATA | include | foreach | choose | if | bind | filter)*>
<!ATTLIST mongo
        id CDATA #REQUIRED
        result-class CDATA #IMPLIED>

<!ELEMENT where (#PCDATA | include | where | foreach | choose | if | bind)*>
<!ELEMENT filter (#PCDATA | include | foreach | choose | if | bind)*>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

<!ELEMENT include (#PCDATA)*>
<!ATTLIST include ref-id CDATA #REQUIRED>

<!ELEMENT foreach (#PCDATA)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | where | foreach | choose | if | bind)*>
<!ATTLIST when test CDATA #REQUIRED>
<!ELEMENT otherwise (#PCDATA | include | where | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | where | foreach | choose | if | bind)*>
<!ATTLIST if test CDATA #REQUIRED>

=== ebinsu/core-framework/core-framework-test/core-framework-test-web/src/main/java/com/example/demo/query/BOMerchandiseQueryV2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE named-queries SYSTEM "src/main/resources/namedquery.dtd">

<named-queries namespace="BOMerchandise1">
    <fragment id="listWhere">
        <where>
            <if test="name!=null">
                m.name like :name
            </if>
        </where>
    </fragment>

    <sql id="list">
        select
        id,
        name,
        price,
        main_image_key mainImageKey,
        description,
        publish
        from
        merchandise m
        <include ref-id="listWhere"/>
    </sql>

    <sql id="list.total">
        select
        count(*) total
        from
        merchandise m
        <include ref-id="listWhere"/>
    </sql>

    <sql id="get">
        select
        id,
        name,
        price,
        main_image_key mainImageKey,
        description,
        publish
        from
        merchandise m
        where m.id = :id
    </sql>

    <sql id="getDetailImages" result-class="java.lang.String">
        select
        image_key
        from
        merchandise_detail_image_keys m
        where m.merchandise_id = :id
    </sql>

</named-queries>

=== ebinsu/core-framework/core-modules/core-modules-name-query/core-modules-name-query-jpa/src/test/resources/TestQuery.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE named-queries SYSTEM "namedquery.dtd">

<named-queries namespace="test">
    <fragment id="f1">
        <where>
            <if test="name!=null">
                name = #{name}
            </if>
        </where>
    </fragment>

    <sql id="1" result-class="java.util.Map">
        SELECT id as "id",name as "name" FROM test
        <include ref-id="f1"/>
    </sql>

    <sql id="1.total">
        SELECT count(*) FROM test
        <include ref-id="f1"/>
    </sql>

    <sql id="2" result-class="java.lang.String">
        SELECT name FROM test
    </sql>
</named-queries>
